"""Generating a sales report with optional additional details function with **kwargs"""

def generate_sales_report(sales_data,**kwargs):
    print("Sales Report")
    print(f"{'Product':<20} {'Quantity':>8}")
    print("="*30)
    for key, value in sales_data.items():
        print(f"{key:<20} {value:>8}")

    print(" ")
    print("Additional Details")

    for key, value in kwargs.items():
        print(f"{key} : {value}")

sales_data = {
    "Product A": 10,
    "Product B": 20,
    "Product C": 15,
}

additional_details = {
    "Report Date"  :  "2025-08-15",
    "Generated by" : "Radovan Tirol",
}

generate_sales_report(sales_data, **additional_details)


if __name__ == "__main__":  #it won’t suddenly ask for input
    generate_sales_report()